apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.clusterName }}
spec:
  instances: {{ .Values.instances }}
  imageName: {{ .Values.imageName }}
  storage:
    size: {{ .Values.storage.size }}
  resources:
    {{- toYaml .Values.resources | nindent 4 }}
  managed:
    roles:
    {{- range .Values.databases }}
      - name: {{ .owner }}
        ensure: present
        login: true
        passwordSecret:
          name: {{ .passwordSecret }}
    {{- end }}
